version: "3.9"

services:
  app:
    build: .
    ports:
      - "8889:8889"
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8889
      DB_HOST: localhost
      PG_USERNAME: postgres
      PG_PASSWORD: qwerty
      PG_PORT: 5432
      PG_BNAME: graphql_api_posts
      PG_SSLMODE: disable
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: graphql_api_posts
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: