// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        int        `json:"id"`
	PostID    int        `json:"postId"`
	AuthorID  int        `json:"authorId"`
	Content   string     `json:"content"`
	CreatedAt string     `json:"createdAt"`
	ParentID  *int       `json:"parentId,omitempty"`
	Replies   []*Comment `json:"replies,omitempty"`
}

type CommentInput struct {
	Content  string `json:"content"`
	ParentID *int   `json:"parentId,omitempty"`
}

type Mutation struct {
}

type PaginationInput struct {
	Limit int `json:"limit"`
	Page  int `json:"page"`
}

type Post struct {
	ID         int        `json:"id"`
	AuthorID   int        `json:"authorId"`
	Title      string     `json:"title"`
	Content    string     `json:"content"`
	CreatedAt  string     `json:"createdAt"`
	Comments   []*Comment `json:"comments,omitempty"`
	CanComment bool       `json:"canComment"`
}

type PostInput struct {
	Title      string `json:"title"`
	Content    string `json:"content"`
	CanComment bool   `json:"canComment"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID       int        `json:"id"`
	Username string     `json:"username"`
	Posts    []*Post    `json:"posts,omitempty"`
	Comments []*Comment `json:"comments,omitempty"`
}
